theme: jekyll-theme-cayman
title: Timothy Helton
email: timothy.j.helton@gmail.com
url: "https://timothyhelton.github.io/"
twitter_username: @T1M_Helton
github_username: TimothyHelton
linkedin: timothy---helton
